import secrets

CACHE_DATE_KEY = 'date'

ICLOUD_CACHE_FILE = ''
ICLOUD_CACHE_LIFETIME = 100
ICLOUD_USERNAME = secrets.ICLOUD_USERNAME
ICLOUD_PASSWORD = secrets.ICLOUD_PASSWORD
ICLOUD_DEVICE_NAME_PREFIX = 'A.'
ICLOUD_FILTERED_DEVICE_TYPES = ['iPhone 7 Plus', 'iPhone 5']

ICLOUD_DEVICE_NAME_KEY = 'name'
ICLOUD_DEVICE_BATTERY_KEY = 'batteryLevel'
ICLOUD_DEVICE_TYPE_KEY = 'deviceDisplayName'
ICLOUD_DEVICE_LAT_KEY = 'latitude'
ICLOUD_DEVICE_LON_KEY = 'longitude'

THEATRE_CACHE_FILE = ''
THEATRE_CACHE_LIFETIME = 100
THEATRE_API_URL = secrets.THEATRE_API_URL

THEATRE_EVENTS_KEY = 'events'
THEATRE_EVENT_NAME_KEY = 'name'
THEATRE_EVENT_DATE_KEY = 'date'


WEATHER_CACHE_FILE = ''
WEATHER_CACHE_LIFETIME = 100
WEATHER_API_KEY = secrets.WEATHER_API_KEY
WEATHER_CURRENT_CITY = 'Evanston'